### ISSUE TITLE
Sticky TODO

### ISSUE THREAD

**Issue by spacekookie** [spacekookie/librobohash#3]
Some things that still need to be done
- [X] Implement hashing context that can be re-used
- [X] Sha512 hashes
- [X] Sha256 hashes
- [ ] Add salt that is persistent over context lifetime
- [X] Compile list of part-names
- [ ] Use libpng to assemble robot in C
  - [ ] Write to file
  - [ ] ???
